### PR TITLE
Improve: relationship keys

### PR DESCRIPTION
**Pull request by NSElvis**
Change `id` for `index`, `NSString` for `NSNumber`.

### CODE REVIEW

**Comment by jgorset** [comment]
Are you ready to merge this, @NSElvis?

**Comment by jgorset** [comment]
I like to bump the version is a separate commit myself. It's easier to keep track of that way.

**Comment by NSElvis** [comment]
@jgorset it's ready, I was just waiting until I had time to do the migration on the other app.

**Comment by NSElvis** [comment]
@jgorset: Yes, it's ready

**Comment by NSElvis** [comment]
@zenangst: Breaking change here

**Comment by zenangst** [comment]
Oh, nifty with the index thing.

**Pull request merged**
